<a href="https://colab.research.google.com/github/KrushnaTaur/ML-Practice/blob/main/02_Data_Preprocessing/06_Feature_Splitting_and_Export.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
data = {
    'Age': [22, 25, 30, 35, 40, 45, 50, 28, 32, 38],
    'Salary': [25000, 27000, 30000, 35000, 40000, 45000, 48000, 29000, 32000, 37000],
    'Experience': [1, 2, 3, 5, 7, 8, 10, 2, 4, 6],
    'Purchased': [0, 0, 1, 1, 1, 1, 1, 0, 0, 1]  # Target column
}

df = pd.DataFrame(data)
df

   Age  Salary  Experience  Purchased
0   22   25000           1          0
1   25   27000           2          0
2   30   30000           3          1
3   35   35000           5          1
4   40   40000           7          1
5   45   45000           8          1
6   50   48000          10          1
7   28   29000           2          0
8   32   32000           4          0
9   38   37000           6          1

In [3]:
# Split Features (X) and Labels (y)
X = df[['Age', 'Salary', 'Experience']]  # Independent variables
y = df['Purchased']                      # Target variable

print("Features (X):\n", X.head())
print("\nLabels (y):\n", y.head())

Features (X):
    Age  Salary  Experience
0   22   25000           1
1   25   27000           2
2   30   30000           3
3   35   35000           5
4   40   40000           7

Labels (y):
 0    0
1    0
2    1
3    1
4    1
Name: Purchased, dtype: int64

In [4]:
# Train-Test Split (80/20 ratio)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)

Training Features Shape: (8, 3)
Testing Features Shape: (2, 3)

In [5]:
# Combine and Export
# Combine X_train and y_train (and same for test) before exporting:

train_df = pd.concat([X_train, y_train], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)

# Export to CSV
train_df.to_csv('train_data.csv', index=False)
test_df.to_csv('test_data.csv', index=False)

print("Files exported successfully!")

Files exported successfully!

In [6]:
# Load back to verify
train_loaded = pd.read_csv('train_data.csv')
test_loaded = pd.read_csv('test_data.csv')

print("Training Data Loaded:\n", train_loaded.head())
print("\nTesting Data Loaded:\n", test_loaded.head())

Training Data Loaded:
    Age  Salary  Experience  Purchased
0   45   45000           8          1
1   22   25000           1          0
2   28   29000           2          0
3   30   30000           3          1
4   38   37000           6          1

Testing Data Loaded:
    Age  Salary  Experience  Purchased
0   32   32000           4          0
1   25   27000           2          0

In [8]:
# Mini Task
import pandas as pd
from sklearn.model_selection import train_test_split

data = {
    'Age': [22, 25, 30, 35, 40, 45, 50, 28, 32, 38],
    'Salary': [25000, 27000, 30000, 35000, 40000, 45000, 48000, 29000, 32000, 37000],
    'Experience': [1, 2, 3, 5, 7, 8, 10, 2, 4, 6],
    'Purchased': [0, 0, 1, 1, 1, 1, 1, 0, 0, 1]
}
df = pd.DataFrame(data)

# Split Features & Labels
X = df[['Age', 'Salary', 'Experience']]
y = df['Purchased']

# Train-Test Split (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Export
train_df = pd.concat([X_train, y_train], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)

train_df.to_csv('train_data.csv', index=False)
test_df.to_csv('test_data.csv', index=False)

print("Train & Test data exported successfully!")

Train & Test data exported successfully!